development:
  adapter: mysql2
  sock: /tmp/mysql.sock
  database: livewatchleads
  pool: 5

production:
  adapter: mysql2
  sock: /tmp/mysql.sock
  database: livewatchleads
  pool: 5

test:
  adapter: mysql2
  sock: /tmp/mysql.sock
  database: livewatchleads_test
  pool: 5
